version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
